### ISSUE TITLE
Fails to compile with miniupnpc 1.9

### ISSUE THREAD

**Issue by acerix** [dogecoin/dogecoin#1292]
Here's the upsteam patch to fix:

https://github.com/bitcoin/bitcoin/commit/9f3e48e5219a09b5ddfd6883d1f0498910eff4b6.patch

The error is:

    CXX      rpcblockchain.o
    net.cpp: In function ‘void ThreadMapPort()’:
    net.cpp:1115:74: error: invalid conversion from ‘int*’ to ‘unsigned char’ [-fpermissive]
         devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
                                                                              ^
    net.cpp:1115:74: error: too few arguments to function ‘UPNPDev* upnpDiscover(int, const char*, const char*, int, int, unsigned char, int*)’
    In file included from net.cpp:24:0:
    /usr/include/miniupnpc/miniupnpc.h:62:1: note: declared here
     upnpDiscover(int delay, const char * multicastif,
     ^
    Makefile:863: recipe for target 'net.o' failed

https://aur.archlinux.org/packages/dogecoin-qt/
https://aur.archlinux.org/packages/dogecoin-daemon/

I was looking at submitting this as a pull request, but I'm not sure which branch it should go in.

**Comment by patricklodder** [comment]
@acerix thank you for raising this. 

You can submit your PR against the `1.8.3-dev` branch

**Comment by patricklodder** [comment]
fixed on 1.10, waiting for your rebase for 1.8.3.

**Comment by patricklodder** [comment]
fixed! thx for your contribution!
