### ISSUE TITLE
Unable to build on ubuntu 16.10 with qt5

### ISSUE THREAD

**Issue by pztrn** [dogecoin/dogecoin#1356]
From just-git-pulled bb4b082c086689434d67490a15224c42fefdfd13. Got many errors like:

```
CXX      qt/qt_libbitcoinqt_a-bitcoinamountfield.o
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h:37:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:40,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qvalidator.h:38,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/QValidator:1,
                 from qt/bitcoinaddressvalidator.h:8,
                 from qt/bitcoinaddressvalidator.cpp:5:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1087:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
```

Configure line was:

```
./configure --with-incompatible-bdb --enable-upnp-default --enable-hardening
```

**Comment by patricklodder** [comment]
It's better to use our supplied dependency libraries than your system defaults, also ensures bdb portability. from the repo root dir:

```
make clean
pushd depends
make
popd
./configure --prefix=`pwd`/depends/x86_64-unknown-linux-gnu
make
```

**Comment by pztrn** [comment]
Tried that, and then got 404 Not Found for protobuf-2.5.0.tar.bz2.

**Comment by patricklodder** [comment]
I have submitted a fix for the depends issue. You can test and/or use it directly by doing:

```
git fetch origin pull/1358/head:pr-1358
git checkout pr-1358
```

and then perform the process from my previous comment. I tested by downloading all dependencies  from a clean depends dir, which worked for me (on linux-x86_64), so this process should work now. 

Please let us know if this works for you now, or if you run into any more issues.

**Comment by pztrn** [comment]
Yep, everything built.

The only "sad" that it doesn't respect systemwide Qt theme.

**Comment by patricklodder** [comment]
That's good to hear (that it compiles.) We have one more blocking CI issue, then we can look into merging the dependencies patch. I'm closing this issue.

In order to support Qt theming we'll need to attract a developer for it. If this is something you and/or others would really like to see, I suggest you create a new issue here for that and we discuss it separately.

Thank you for the feedback.
