### ISSUE TITLE
Depreciation warning for boost 1.82

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#3211]
While I was testing #3207 with boost 1.81, I noticed this warning:

```
In file included from /usr/include/boost/math/tools/series.hpp:16,
                 from /usr/include/boost/math/special_functions/gamma.hpp:17,
                 from /usr/include/boost/math/distributions/poisson.hpp:40,
                 from validation.cpp:51:
/usr/include/boost/math/tools/config.hpp:23:6: warning: #warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)" [-Wcpp]
   23 | #    warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)"
      |      ^~~~~~~
```

Since 1.14 is standardized on c++11, we may face issues to compile with boost 1.82 in the future.

**Comment by sinetek** [comment]
boost 1.82 breaks at compile-time things too numerous to list here. In my opinion this is an important ticket.

**Comment by sinetek** [comment]
```
bench/bench.h: In constructor ‘benchmark::State::State(std::string, double)’:
bench/bench.h:52:28: error: ‘numeric_limits’ is not a member of ‘std’
   52 |             minTime = std::numeric_limits<double>::max();
      |                            ^~~~~~~~~~~~~~
```

**Comment by sinetek** [comment]
Never mind that, I think it compiled successfully.  I got the warning about C++14 too.

```
In file included from /home/pmb/dogecoin/depends/x86_64-pc-linux-gnu/share/../include/boost/math/tools/series.hpp:16,
                 from /home/pmb/dogecoin/depends/x86_64-pc-linux-gnu/share/../include/boost/math/special_functions/gamma.hpp:17,
                 from /home/pmb/dogecoin/depends/x86_64-pc-linux-gnu/share/../include/boost/math/distributions/poisson.hpp:40,
                 from validation.cpp:51:
/home/pmb/dogecoin/depends/x86_64-pc-linux-gnu/share/../include/boost/math/tools/config.hpp:23:6: warning: #warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)" [-Wcpp]
   23 | #    warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)"
      |      ^~~~~~~
```
