### ISSUE TITLE
boost 1.74 - validation.cpp:182:111: error: ‘_1’ was not declared in this scope

### ISSUE THREAD

**Issue by bjacquin** [dogecoin/dogecoin#1654]
Hi,

dogecoin 1.14.2 fails to build with boost 1.74.0 with the following error:

```
x86_64-pc-linux-gnu-g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config   -I. -I./obj -I/usr/include/db5.1/ -pthread -I/usr/include -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include    -pthread -I/usr/include/db5.1 -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS    -march=native -O2 -pipe -fomit-frame-pointer -c -o libdogecoin_server_a-validation.o `test -f 'validation.cpp' || echo './'`validation.cpp
In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from primitives/block.h:15,
                 from chain.h:10,
                 from validation.h:14,
                 from validation.cpp:6:
/usr/include/boost/function_output_iterator.hpp:14:1: note: #pragma message: This header is deprecated. Use <boost/iterator/function_output_iterator.hpp> instead.
   14 | BOOST_HEADER_DEPRECATED("<boost/iterator/function_output_iterator.hpp>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
validation.cpp: In constructor ‘MemPoolConflictRemovalTracker::MemPoolConflictRemovalTracker(CTxMemPool&)’:
validation.cpp:182:111: error: ‘_1’ was not declared in this scope
  182 |         pool.NotifyEntryRemoved.connect(boost::bind(&MemPoolConflictRemovalTracker::NotifyEntryRemoved, this, _1, _2));
      |                                                                                                               ^~
validation.cpp:182:111: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_adaptor.hpp:14,
                 from /usr/include/boost/iterator/reverse_iterator.hpp:10,
                 from /usr/include/boost/range/reverse_iterator.hpp:21,
                 from /usr/include/boost/range/rend.hpp:19,
                 from /usr/include/boost/foreach.hpp:82,
                 from memusage.h:16,
                 from core_memusage.h:10,
                 from coins.h:10,
                 from validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/boost/smart_ptr/detail/shared_count.hpp:37,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:17,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from primitives/block.h:15,
                 from chain.h:10,
                 from validation.h:14,
                 from validation.cpp:6:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/functional:211:34: note:   ‘std::placeholders::_1’
  211 |     extern const _Placeholder<1> _1;
      |                                  ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_adaptor.hpp:14,
                 from /usr/include/boost/iterator/reverse_iterator.hpp:10,
                 from /usr/include/boost/range/reverse_iterator.hpp:21,
                 from /usr/include/boost/range/rend.hpp:19,
                 from /usr/include/boost/foreach.hpp:82,
                 from memusage.h:16,
                 from core_memusage.h:10,
                 from coins.h:10,
                 from validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/boost/bind/bind.hpp:2356,
                 from /usr/include/boost/signals2/slot.hpp:15,
                 from /usr/include/boost/signals2/connection.hpp:24,
                 from /usr/include/boost/signals2/signal.hpp:22,
                 from util.h:29,
                 from dbwrapper.h:11,
                 from txdb.h:10,
                 from validation.cpp:31:
/usr/include/boost/bind/placeholders.hpp:46:38: note:   ‘boost::placeholders::_1’
   46 | BOOST_STATIC_CONSTEXPR boost::arg<1> _1;
      |                                      ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_adaptor.hpp:14,
                 from /usr/include/boost/iterator/reverse_iterator.hpp:10,
                 from /usr/include/boost/range/reverse_iterator.hpp:21,
                 from /usr/include/boost/range/rend.hpp:19,
                 from /usr/include/boost/foreach.hpp:82,
                 from memusage.h:16,
                 from core_memusage.h:10,
                 from coins.h:10,
                 from validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
validation.cpp:182:115: error: ‘_2’ was not declared in this scope
  182 |         pool.NotifyEntryRemoved.connect(boost::bind(&MemPoolConflictRemovalTracker::NotifyEntryRemoved, this, _1, _2));
      |                                                                                                                   ^~
validation.cpp:182:115: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_adaptor.hpp:14,
                 from /usr/include/boost/iterator/reverse_iterator.hpp:10,
                 from /usr/include/boost/range/reverse_iterator.hpp:21,
                 from /usr/include/boost/range/rend.hpp:19,
                 from /usr/include/boost/foreach.hpp:82,
                 from memusage.h:16,
                 from core_memusage.h:10,
                 from coins.h:10,
                 from validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
In file included from /usr/include/boost/smart_ptr/detail/shared_count.hpp:37,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:17,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from primitives/block.h:15,
                 from chain.h:10,
                 from validation.h:14,
                 from validation.cpp:6:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/functional:212:34: note:   ‘std::placeholders::_2’
  212 |     extern const _Placeholder<2> _2;
      |                                  ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_adaptor.hpp:14,
                 from /usr/include/boost/iterator/reverse_iterator.hpp:10,
                 from /usr/include/boost/range/reverse_iterator.hpp:21,
                 from /usr/include/boost/range/rend.hpp:19,
                 from /usr/include/boost/foreach.hpp:82,
                 from memusage.h:16,
                 from core_memusage.h:10,
                 from coins.h:10,
                 from validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
In file included from /usr/include/boost/bind/bind.hpp:2356,
                 from /usr/include/boost/signals2/slot.hpp:15,
                 from /usr/include/boost/signals2/connection.hpp:24,
                 from /usr/include/boost/signals2/signal.hpp:22,
                 from util.h:29,
                 from dbwrapper.h:11,
                 from txdb.h:10,
                 from validation.cpp:31:
/usr/include/boost/bind/placeholders.hpp:47:38: note:   ‘boost::placeholders::_2’
   47 | BOOST_STATIC_CONSTEXPR boost::arg<2> _2;
      |                                      ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_adaptor.hpp:14,
                 from /usr/include/boost/iterator/reverse_iterator.hpp:10,
                 from /usr/include/boost/range/reverse_iterator.hpp:21,
                 from /usr/include/boost/range/rend.hpp:19,
                 from /usr/include/boost/foreach.hpp:82,
                 from memusage.h:16,
                 from core_memusage.h:10,
                 from coins.h:10,
                 from validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
validation.cpp: In destructor ‘MemPoolConflictRemovalTracker::~MemPoolConflictRemovalTracker()’:
validation.cpp:192:114: error: ‘_1’ was not declared in this scope
  192 |         pool.NotifyEntryRemoved.disconnect(boost::bind(&MemPoolConflictRemovalTracker::NotifyEntryRemoved, this, _1, _2));
      |                                                                                                                  ^~
validation.cpp:192:114: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_adaptor.hpp:14,
                 from /usr/include/boost/iterator/reverse_iterator.hpp:10,
                 from /usr/include/boost/range/reverse_iterator.hpp:21,
                 from /usr/include/boost/range/rend.hpp:19,
                 from /usr/include/boost/foreach.hpp:82,
                 from memusage.h:16,
                 from core_memusage.h:10,
                 from coins.h:10,
                 from validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/boost/smart_ptr/detail/shared_count.hpp:37,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:17,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from primitives/block.h:15,
                 from chain.h:10,
                 from validation.h:14,
                 from validation.cpp:6:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/functional:211:34: note:   ‘std::placeholders::_1’
  211 |     extern const _Placeholder<1> _1;
      |                                  ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_adaptor.hpp:14,
                 from /usr/include/boost/iterator/reverse_iterator.hpp:10,
                 from /usr/include/boost/range/reverse_iterator.hpp:21,
                 from /usr/include/boost/range/rend.hpp:19,
                 from /usr/include/boost/foreach.hpp:82,
                 from memusage.h:16,
                 from core_memusage.h:10,
                 from coins.h:10,
                 from validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/boost/bind/bind.hpp:2356,
                 from /usr/include/boost/signals2/slot.hpp:15,
                 from /usr/include/boost/signals2/connection.hpp:24,
                 from /usr/include/boost/signals2/signal.hpp:22,
                 from util.h:29,
                 from dbwrapper.h:11,
                 from txdb.h:10,
                 from validation.cpp:31:
/usr/include/boost/bind/placeholders.hpp:46:38: note:   ‘boost::placeholders::_1’
   46 | BOOST_STATIC_CONSTEXPR boost::arg<1> _1;
      |                                      ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_adaptor.hpp:14,
                 from /usr/include/boost/iterator/reverse_iterator.hpp:10,
                 from /usr/include/boost/range/reverse_iterator.hpp:21,
                 from /usr/include/boost/range/rend.hpp:19,
                 from /usr/include/boost/foreach.hpp:82,
                 from memusage.h:16,
                 from core_memusage.h:10,
                 from coins.h:10,
                 from validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
validation.cpp:192:118: error: ‘_2’ was not declared in this scope
  192 |         pool.NotifyEntryRemoved.disconnect(boost::bind(&MemPoolConflictRemovalTracker::NotifyEntryRemoved, this, _1, _2));
      |                                                                                                                      ^~
validation.cpp:192:118: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_adaptor.hpp:14,
                 from /usr/include/boost/iterator/reverse_iterator.hpp:10,
                 from /usr/include/boost/range/reverse_iterator.hpp:21,
                 from /usr/include/boost/range/rend.hpp:19,
                 from /usr/include/boost/foreach.hpp:82,
                 from memusage.h:16,
                 from core_memusage.h:10,
                 from coins.h:10,
                 from validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
In file included from /usr/include/boost/smart_ptr/detail/shared_count.hpp:37,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:17,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from primitives/block.h:15,
                 from chain.h:10,
                 from validation.h:14,
                 from validation.cpp:6:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/functional:212:34: note:   ‘std::placeholders::_2’
  212 |     extern const _Placeholder<2> _2;
      |                                  ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_adaptor.hpp:14,
                 from /usr/include/boost/iterator/reverse_iterator.hpp:10,
                 from /usr/include/boost/range/reverse_iterator.hpp:21,
                 from /usr/include/boost/range/rend.hpp:19,
                 from /usr/include/boost/foreach.hpp:82,
                 from memusage.h:16,
                 from core_memusage.h:10,
                 from coins.h:10,
                 from validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
In file included from /usr/include/boost/bind/bind.hpp:2356,
                 from /usr/include/boost/signals2/slot.hpp:15,
                 from /usr/include/boost/signals2/connection.hpp:24,
                 from /usr/include/boost/signals2/signal.hpp:22,
                 from util.h:29,
                 from dbwrapper.h:11,
                 from txdb.h:10,
                 from validation.cpp:31:
/usr/include/boost/bind/placeholders.hpp:47:38: note:   ‘boost::placeholders::_2’
   47 | BOOST_STATIC_CONSTEXPR boost::arg<2> _2;
      |                                      ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_adaptor.hpp:14,
                 from /usr/include/boost/iterator/reverse_iterator.hpp:10,
                 from /usr/include/boost/range/reverse_iterator.hpp:21,
                 from /usr/include/boost/range/rend.hpp:19,
                 from /usr/include/boost/foreach.hpp:82,
                 from memusage.h:16,
                 from core_memusage.h:10,
                 from coins.h:10,
                 from validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
make[2]: *** [Makefile:6352: libdogecoin_server_a-validation.o] Error 1
make[2]: Leaving directory '/var/tmp/portage/net-p2p/dogecoin-1.14.2/work/dogecoin-1.14.2/src'
make[1]: *** [Makefile:9720: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/net-p2p/dogecoin-1.14.2/work/dogecoin-1.14.2/src'
make: *** [Makefile:686: all-recursive] Error 1
```

**Comment by John-Gee** [comment]
You just need to add 

> #include <boost/bind.hpp>

to those files where it fails. I'm guessing there was some boost reorg or something.

**Comment by crozone** [comment]
> 
> 
> You just need to add
> 
> > #include <boost/bind.hpp>
> 
> to those files where it fails. I'm guessing there was some boost reorg or something.

This gives the warning:

```
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
```

Definitely something to improve since this update will be required for debian bullseye

**Comment by vertiond** [comment]
Building Dogecoin using the depends system is the way to go.

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin Close this one.

**Comment by patricklodder** [comment]
Fixed with #1655
